# https://en.wikipedia.org/wiki/List_of_trigonometric_identities
# COMMON
"""
sin²(x)+cos²(x)=1
1+cot²(x)=csc²(x)
1+tan²(x)=sec²(x)
sec²(x)+csc²(x)=sec²(x)csc²(x)
csc(x)=1/sin(x)
sec(x)=1/cos(x)
cot(x)=1/tan(x)
"""
# REFLECTIONS
"""
sin(-x)=-sin(x)
cos(-x)=cos(x)
tan(-x)=-tan(x)
csc(-x)=-csc(x)
sec(-x)=sec(x)
cot(-x)=-cot(x)
sin(pi/2-x)=cos(x)
cos(pi/2-x)=sin(x)
tan(pi/2-x)=cot(x)
csc(pi/2-x)=sec(x)
sec(pi/2-x)=csc(x)
cot(pi/2-x)=tan(x)
sin(pi-x)=sin(x)
cos(pi-x)=-cos(x)
tan(pi-x)=-tan(x)
csc(pi-x)=csc(x)
sec(pi-x)=-sec(x)
cot(pi-x)=-cot(x)
sin(3pi/2-x)=-cos(x)
cos(3pi/2-x)=-sin(x)
tan(3pi/2-x)=cot(x)
csc(3pi/2-x)=-sec(x)
sec(3pi/2-x)=-csc(x)
cot(3pi/2-x)=tan(x)
"""
# PERIODIC
"""
f(x+2pik)=f(x), tan&cot->2k
sin(x±pi/2)=±cos(x)
cos(x±pi/2)=±°sin(x)
csc(x±pi/2)=±sec(x)
sec(x±pi/2)=±°csc(x)
tan(x±pi/4)=(tan(x)±1)/(1±°tan(x))
cot(x±pi/4)=(cot(x)±°1)/(1±cot(x))
sin(x+pi)=-sin(x)
cos(x+pi)=-cos(x)
csc(x+pi)=-csc(x)
sec(x+pi)=-sec(x)
tan(x+pi)=tan(x)
cot(x+pi)=cot(x)
"""
# ANGLE SUM
"""
sin(A±B)=sin(A)cos(B)±cos(A)sin(B)
cos(A±B)=cos(A)cos(B)±°sin(A)sin(B)
tan(A±B)=(tan(A)±tan(B))/(1±°tan(A)tan(B))
csc(A±B)=(sec(A)sec(B)csc(A)csc(B))/(sec(A)csc(B)±csc(A)sec(B))
sec(A±B)=(sec(A)sec(B)csc(A)csc(B))/(csc(A)csc(B)±°sec(A)sec(B))
cot(A±B)=(cot(A)cot(B)±°1)/(cot(B)±cot(A))
arcsin(x)±arcsin(y)=arcsin(xsqrt(1-y²)±ysqrt(1-x²))
arccos(x)±arccos(y)=arccos(xy±°sqrt((1-x²)(1-y²)))
arctan(x)±arctan(y)=arctan((x±y)/(1±°xy))
arccot(x)±arccot(y)=arccot((xy±1)/(y±x))
"""
# MULTI-ANGLE
"""
cos(nx)+isin(nx)=(cos(x)+isin(x))^n
sin(2x)=2sin(x)cos(x)=(sin(x)+cos(x))²-1=(2tan(x))/(1+tan²(x))
cos(2x)=cos²(x)-sin²(x)=2cos²(x)-1=1-2sin²(x)=(1-tan²(x))/(1+tan²(x))
tan(2x)=(2tan(x))/(1-tan²(x))
cot(2x)=(cot²(x)-1)/(2cot(x))=(1-tan²(x))/(2tan(x))
sec(2x)=(sec²(x))/(2-sec²(x))=(1+tan²(x))/(1-tan²(x))
csc(2x)=(sec(x)csc(x))/2=(1+tan²(x))/(2tan(x))
sin(3x)=3sin(x)-4sin³(x)=4sin(x)sin(pi/3-x)sin(pi/3+x)
cos(3x)=4cos³(x)-3cos(x)=4cos(x)cos(pi/3-x)cos(pi/3+x)
tan(3x)=(3tan(x)-tan³(x))/(1-3tan²(x))=tan(x)tan(pi/3-x)tan(pi/3+x)
cot(3x)=(3cot(x)-cot³(x))/(1-3cot²(x))
sec(3x)=sec³(x)/(4-3sec²(x))
csc(3x)=csc³(x)/(3csc²(x)-4
"""
# HALF-ANGLE
"""
sin(x/2)=sgn(sin(x/2))sqrt((1-cos(x))/2)
cos(x/2)=sgn(cos(x/2))sqrt((1+cos(x))/2)
tan(x/2)=(1-cos(x))/sin(x)=sin(x)/(1+cos(x))=csc(x)-cot(x)=tan(x)/(1+sec(x))
tan(x/2)=sgn(sin(x))sqrt((1-cos(x))/(1+cos(x)))=(-1+sgn(cos(x))sqrt(1+tan²(x)))/tan(x)
cot(x/2)=(1+cos(x))/sin(x)=sin(x)/(1-cos(x))=csc(x)+cot(x)=sgn(sin(x))sqrt((1+cos(x))/(1-cos(x)))
sec(x/2)=sgn(cos(x/2))sqrt(2/(1+cos(x)))
csc(x/2)=sgn(sin(x/2))sqrt(2/(1-cos(x)))
tan((a±x)/2)=(sin(a)±sin(x))/(cos(a)+cos(x))
tan(x/2+pi/4)=sec(x)+tan(x)
sqrt((1-sin(x))/(1+sin(x)))=|(1-tan(x/2))|/|(1+tan(x/2))|
"""
# POWER REDUCTION
"""
sin²(x)=(1-cos(2x))/2
cos²(x)=(1+cos(2x))/2
sin²(x)cos²(x)=(1-cos(4x))/8
sin³(x)=(3sin(x)-sin(3x))/4
cos³(x)=(3cos(x)+cos(3x))/4
sin³(x)cos³(x)=(3sin(2x)-sin(6x))/32
sin^4(x)=(3-4cos(2x)+cos(4x))/8
cos^4(x)=(3+4cos(2x)+cos(4x))/8
sin^4(x)cos^4(x)=(3-4cos(4x)+cos(8x))/128
sin^5(x)=(10sin(x)-5sin(3x)+sin(5x))/16
cos^5(x)=(10cos(x)+5cos(3x)+cos(5x))/16
sin^5(x)cos^5(x)=(10sin(2x)-5sin(6x)+sin(10x))/512
"""
# PROD TO SUM
"""
cos(A)*cos(B)=(1/2)*(cos(A-B)+cos(A+B))
sin(A)*sin(B)=(1/2)*(cos(A-B)-cos(A+B))
sin(A)*cos(B)=(1/2)*(sin(A+B)+sin(A-B))
cos(A)*sin(B)=(1/2)*(sin(A+B)-sin(A-B))
tan(A)*tan(B)=(cos(A-B)-cos(A+B))/(cos(A-B)+cos(A+B))
tan(A)*cot(B)=(sin(A+B)+sin(A-B))/(sin(A+B)-sin(A-B))
sin(A)±sin(B)=2sin((A±B)/2)cos((A±°B)/2)
cos(A)+cos(B)=2cos((A+B)/2)cos((A-B)/2)
cos(A)-cos(B)=-2sin((A+B)/2)sin((A-B)/2)
tan(A)±tan(B)=sin(A±B)/(cos(A)*cos(B))
"""