# https://en.wikipedia.org/wiki/List_of_trigonometric_identities
def main():
    print("1. COMMON")
    print("2. REFLECTIONS")
    print("3. PERIODIC")
    print("4. ANGLE SUM")
    print("5. MULTI-ANGLE")
    print("6. HALF-ANGLE")
    print("7. POWER REDUCTION")
    print("8. PROD TO SUM")
    sel = input("CHOOSE CATEGORY: ")
    if sel == "1":
        print("sin²(x)+cos²(x)=1")
        print("1+cot²(x)=csc²(x)")
        print("1+tan²(x)=sec²(x)")
        print("sec²(x)+csc²(x)=sec²(x)csc²(x)")
        print("csc(x)=1/sin(x)")
        print("sec(x)=1/cos(x)")
        print("cot(x)=1/tan(x)")
    elif sel == "2":
        print("sin(-x)=-sin(x)")
        print("cos(-x)=cos(x)")
        print("tan(-x)=-tan(x)")
        print("csc(-x)=-csc(x)")
        print("sec(-x)=sec(x)")
        print("cot(-x)=-cot(x)")
        print("sin(pi/2-x)=cos(x)")
        print("cos(pi/2-x)=sin(x)")
        print("tan(pi/2-x)=cot(x)")
        print("csc(pi/2-x)=sec(x)")
        print("sec(pi/2-x)=csc(x)")
        print("cot(pi/2-x)=tan(x)")
        print("sin(pi-x)=sin(x)")
        print("cos(pi-x)=-cos(x)")
        print("tan(pi-x)=-tan(x)")
        print("csc(pi-x)=csc(x)")
        print("sec(pi-x)=-sec(x)")
        print("cot(pi-x)=-cot(x)")
        print("sin(3pi/2-x)=-cos(x)")
        print("cos(3pi/2-x)=-sin(x)")
        print("tan(3pi/2-x)=cot(x)")
        print("csc(3pi/2-x)=-sec(x)")
        print("sec(3pi/2-x)=-csc(x)")
        print("cot(3pi/2-x)=tan(x)")
    elif sel == "3":
        print("f(x+2pik)=f(x), tan&cot->2k")
        print("sin(x±pi/2)=±cos(x)")
        print("cos(x±pi/2)=±°sin(x)")
        print("csc(x±pi/2)=±sec(x)")
        print("sec(x±pi/2)=±°csc(x)")
        print("tan(x±pi/4)=(tan(x)±1)/(1±°tan(x))")
        print("cot(x±pi/4)=(cot(x)±°1)/(1±cot(x))")
        print("sin(x+pi)=-sin(x)")
        print("cos(x+pi)=-cos(x)")
        print("csc(x+pi)=-csc(x)")
        print("sec(x+pi)=-sec(x)")
        print("tan(x+pi)=tan(x)")
        print("cot(x+pi)=cot(x)")
    elif sel == "4":
        print("sin(A±B)=sin(A)cos(B)±cos(A)sin(B)")
        print("cos(A±B)=cos(A)cos(B)±°sin(A)sin(B)")
        print("tan(A±B)=(tan(A)±tan(B))/(1±°tan(A)tan(B))")
        print("csc(A±B)=(sec(A)sec(B)csc(A)csc(B))/(sec(A)csc(B)±csc(A)sec(B))")
        print("sec(A±B)=(sec(A)sec(B)csc(A)csc(B))/(csc(A)csc(B)±°sec(A)sec(B))")
        print("cot(A±B)=(cot(A)cot(B)±°1)/(cot(B)±cot(A))")
        print("arcsin(x)±arcsin(y)=arcsin(xsqrt(1-y²)±ysqrt(1-x²))")
        print("arccos(x)±arccos(y)=arccos(xy±°sqrt((1-x²)(1-y²)))")
        print("arctan(x)±arctan(y)=arctan((x±y)/(1±°xy))")
        print("arccot(x)±arccot(y)=arccot((xy±1)/(y±x))")
    elif sel == "5":
        print("cos(nx)+isin(nx)=(cos(x)+isin(x))^n")
        print("sin(2x)=2sin(x)cos(x)=(sin(x)+cos(x))²-1=(2tan(x))/(1+tan²(x))")
        print("cos(2x)=cos²(x)-sin²(x)=2cos²(x)-1=1-2sin²(x)=(1-tan²(x))/(1+tan²(x))")
        print("tan(2x)=(2tan(x))/(1-tan²(x))")
        print("cot(2x)=(cot²(x)-1)/(2cot(x))=(1-tan²(x))/(2tan(x))")
        print("sec(2x)=(sec²(x))/(2-sec²(x))=(1+tan²(x))/(1-tan²(x))")
        print("csc(2x)=(sec(x)csc(x))/2=(1+tan²(x))/(2tan(x))")
        print("sin(3x)=3sin(x)-4sin³(x)=4sin(x)sin(pi/3-x)sin(pi/3+x)")
        print("cos(3x)=4cos³(x)-3cos(x)=4cos(x)cos(pi/3-x)cos(pi/3+x)")
        print("tan(3x)=(3tan(x)-tan³(x))/(1-3tan²(x))=tan(x)tan(pi/3-x)tan(pi/3+x)")
        print("cot(3x)=(3cot(x)-cot³(x))/(1-3cot²(x))")
        print("sec(3x)=sec³(x)/(4-3sec²(x))")
        print("csc(3x)=csc³(x)/(3csc²(x)-4)")
    elif sel == "6":
        print("sin(x/2)=sgn(sin(x/2))sqrt((1-cos(x))/2)")
        print("cos(x/2)=sgn(cos(x/2))sqrt((1+cos(x))/2)")
        print("tan(x/2)=(1-cos(x))/sin(x)=sin(x)/(1+cos(x))=csc(x)-cot(x)=tan(x)/(1+sec(x))")
        print("tan(x/2)=sgn(sin(x))sqrt((1-cos(x))/(1+cos(x)))=(-1+sgn(cos(x))sqrt(1+tan²(x)))/tan(x)")
        print("cot(x/2)=(1+cos(x))/sin(x)=sin(x)/(1-cos(x))=csc(x)+cot(x)=sgn(sin(x))sqrt((1+cos(x))/(1-cos(x)))")
        print("sec(x/2)=sgn(cos(x/2))sqrt(2/(1+cos(x)))")
        print("csc(x/2)=sgn(sin(x/2))sqrt(2/(1-cos(x)))")
        print("tan((a±x)/2)=(sin(a)±sin(x))/(cos(a)+cos(x))")
        print("tan(x/2+pi/4)=sec(x)+tan(x)")
        print("sqrt((1-sin(x))/(1+sin(x)))=|(1-tan(x/2))|/|(1+tan(x/2))|")
    elif sel == "7":
        print("sin²(x)=(1-cos(2x))/2")
        print("cos²(x)=(1+cos(2x))/2")
        print("sin²(x)cos²(x)=(1-cos(4x))/8")
        print("sin³(x)=(3sin(x)-sin(3x))/4")
        print("cos³(x)=(3cos(x)+cos(3x))/4")
        print("sin³(x)cos³(x)=(3sin(2x)-sin(6x))/32")
        print("sin^4(x)=(3-4cos(2x)+cos(4x))/8")
        print("cos^4(x)=(3+4cos(2x)+cos(4x))/8")
        print("sin^4(x)cos^4(x)=(3-4cos(4x)+cos(8x))/128")
        print("sin^5(x)=(10sin(x)-5sin(3x)+sin(5x))/16")
        print("cos^5(x)=(10cos(x)+5cos(3x)+cos(5x))/16")
        print("sin^5(x)cos^5(x)=(10sin(2x)-5sin(6x)+sin(10x))/512")
    elif sel == "8":
        print("cos(A)*cos(B)=(1/2)*(cos(A-B)+cos(A+B))")
        print("sin(A)*sin(B)=(1/2)*(cos(A-B)-cos(A+B))")
        print("sin(A)*cos(B)=(1/2)*(sin(A+B)+sin(A-B))")
        print("cos(A)*sin(B)=(1/2)*(sin(A+B)-sin(A-B))")
        print("tan(A)*tan(B)=(cos(A-B)-cos(A+B))/(cos(A-B)+cos(A+B))")
        print("tan(A)*cot(B)=(sin(A+B)+sin(A-B))/(sin(A+B)-sin(A-B))")
        print("sin(A)±sin(B)=2sin((A±B)/2)cos((A∓B)/2)")
        print("cos(A)+cos(B)=2cos((A+B)/2)cos((A-B)/2)")
        print("cos(A)-cos(B)=-2sin((A+B)/2)sin((A-B)/2)")
        print("tan(A)±tan(B)=sin(A±B)/(cos(A)*cos(B))")

main()